version: '3'

services: 
  app:
    build: .
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun 
    ports:
      - 58846:58846
    volumes:
      - ./ovpn:/ovpn
      - ./downloads:/app/Downloads